name: icesat2-cookbook-dev
channels:
- conda-forge
- nodefaults
dependencies:
- cartopy *
- matplotlib *
- pre-commit *
- jupyterlab *
- jupyterlab-myst *
- dask *
- earthaccess *
- geodatasets *
- geopandas *
- icepyx=2.0.0
- ipympl *
- ipykernel *
- mystmd *
- numpy *
- pyproj *
- rioxarray *
- sliderule *
- xarray *
- h5py *
- geoviews *
- shapely *
- contextily * 
- fiona * 
