name: trigger-link-check
on:
  workflow_run:
    workflows: [trigger-pixi-environment]
    types: [completed]

jobs:
  link-check:
    uses: ProjectPythia/cookbook-actions/.github/workflows/link-checker.yaml@main
